spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/order}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  application:
    name: order-service

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        show_sql: true
        format_sql: true
        ddl-auto: none

  liquibase:
    change-log: classpath:db.master.yml
    enabled: true

  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:29092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

management:
  endpoints.web.exposure.include: 'prometheus, health, info, metric'
  prometheus:
    metrics:
      export:
        enabled: true
      distribution:
        percentiles-histogram:
          "[http.server.requests]" : true